# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  type: ClusterIP