# templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
spec:
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  type: ClusterIP