apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-app-to-postgres-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Chart.Name }}-backend