# templates/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres-service
spec:
  selector:
    app: {{ .Chart.Name }}-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP